// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8bg90-0Hvq98lnUbzLeTdQV-X_pW3beI',
    appId: '1:435400073673:web:5ae2db03c79b2786104818',
    messagingSenderId: '435400073673',
    projectId: 'tuhubread-1e656',
    authDomain: 'tuhubread-1e656.firebaseapp.com',
    storageBucket: 'tuhubread-1e656.firebasestorage.app',
    measurementId: 'G-YP8651Z5V4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqYPqoTYC9EBosXIzdEjeuGiUISufEMTM',
    appId: '1:435400073673:android:7821750f92736117104818',
    messagingSenderId: '435400073673',
    projectId: 'tuhubread-1e656',
    storageBucket: 'tuhubread-1e656.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOikY9iPiHPZXMTQO9RPRlDbjRCgWTyjE',
    appId: '1:435400073673:ios:db8905159dcd2231104818',
    messagingSenderId: '435400073673',
    projectId: 'tuhubread-1e656',
    storageBucket: 'tuhubread-1e656.firebasestorage.app',
    iosBundleId: 'com.example.tuhubread',
  );
}
